---
:header_text: Client scorecard demo
:client_name: Sample Client Inc.
:colors:
- '#59B9EF'
- '#B5D855'
- '#FBC363'
- '#81D8FD'
- '#DE94D4'
- '#F5D048'
- '#90B9D1'
- '#CDC5A5'
- '#50BBCC'
- '#D7DD46'
- '#92ADFE'
